### ISSUE TITLE
Feature to exclude files / directories from analysis

### ISSUE THREAD

**Issue by akito19** [sider/phinder#42]
I seem that Phinder hasn't excluded files and directories, for example `/vendor` directory, from analyses. 
Phinder will be more useful if users can adjust analysis targets in detail.

In case of Querly, `[check](https://github.com/soutaro/querly/blob/41dc3be8a0c9420fc88a4259789b0a8acef45964/manual/configuration.md#check)` feature can control files and directories.

What do you think about it?

**Comment by tomokinakamaru** [comment]
@akito19 Sorry for keeping you waiting.

I am planning to achieve the exclusion feature by adding `ignore` key into `phinder.yml` as follows:
```yml
rule:
  ...
ignore:
  - vendor
  ...
```
Each element in `ignore` works as the same as a line of `.gitignore`.

Querly seems to support more complex configurations such as rule-id filtering. But for the first step in Phinder, I am planning to support only exclusion configuration feature. Does this match your need?

**Comment by wata727** [comment]
In my opinion, the exclude (or include) pattern syntax should be attached to each rule. Perhaps, Goodcheck or RuboCop ways are good for us.

**Goodcheck**

```yaml
  - id: com.example.github
    pattern: Github
    message: |
      GitHub is GitHub, not Github

      You may misspelling the name of the service!
    justification:
      - When you mean a service different from GitHub
      - When GitHub is renamed
    glob:
      - app/views/**/*.html.slim
      - config/locales/**/*.yaml
```

**RuboCop**

```yaml
Bundler/DuplicatedGem:
  Enabled: true
  Include:
    - '**/*.gemfile'
    - '**/Gemfile'
    - '**/gems.rb'
```
