### ISSUE TITLE
Phinder does not match for ctp files

### ISSUE THREAD

**Issue by wata727** [sider/phinder#57]
In v0.8.0, it seems to Phinder does not match for ctp files.

*phinder.yaml*

```yaml
- id: sample.in_array_without_3rd_param
  pattern: in_array(_, _)
  message: Specify 3rd parameter explicitly when calling in_array to avoid unexpected comparison results.
  test:
    fail:
      - in_array(1, $arr);
      - in_array(2, $arr);
    pass:
      - in_array(3, $arr, true);
      - in_array(4, $arr, false);
```

*view.ctp*

```html
<div class='working'>
    <span>Result</span>
    <?= in_array($holiday, $contract) ?>
</div>
```

*output*

```
$ phinder find .
# no results
```
